In [80]:
import numpy as np
import pandas as pd
from tensorflow import keras
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import seaborn as sb
from keras.models import Sequential
from keras.layers import Dense
import sklearn
from sklearn import metrics
from sklearn import preprocessing
print("hello world")


hello world


In [81]:
iris= pd.read_csv(r'C:\Users\aadit\OneDrive\Desktop\IRIS dataset\Iris.csv')
x=iris[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
x=preprocessing.scale(x)
y=iris["Species"].values
enc=LabelEncoder()
Y=pd.get_dummies(enc.fit_transform(y)).values

print(Y.shape)
print(y.shape)
x_train, x_test, y_train,y_test=train_test_split(x,Y,test_size=0.2,stratify=Y)



(150, 3)
(150,)


In [82]:
model=Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [88]:
model.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 2/100
12/12 [==============================] - 0s 4ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 3/100
12/12 [==============================] - 0s 4ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 4/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 5/100
12/12 [==============================] - 0s 6ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 6/100
12/12 [==============================] - 0s 9ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 7/100
12/12 [==============================] - 0s 10ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 8/100
12/12 [==============================] - 0s 9ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 9/100
12/12 [==============================] - 0s 7ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 10/100
12/12 [==============================] - 0s 9ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 11

In [91]:
print(model.evaluate(x_test, y_test))

1/1 [==============================] - 0s 363ms/step - loss: 0.0094 - accuracy: 1.0000
[0.009446212090551853, 1.0]


In [92]:
expected=y_test
expected=np.argmax(expected,axis=1)
prediction=model.predict(x_test)
prediction=np.argmax(prediction,axis=1)

print(metrics.classification_report(expected,prediction))
print(metrics.confusion_matrix(expected,prediction))

1/1 [==============================] - 0s 56ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
